# Generated by Django 5.0.6 on 2024-06-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KindsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_kinds', models.CharField(max_length=30)),
                ('type_kinds', models.CharField(max_length=30)),
                ('prize_kinds', models.IntegerField()),
                ('platform_kinds', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MusicsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
                ('likes_mill', models.FloatField()),
                ('lang', models.CharField(max_length=30)),
                ('song_type', models.CharField(max_length=30)),
                ('prize', models.BooleanField()),
            ],
        ),
    ]
