# Generated by Django 5.0.6 on 2024-06-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoveMusics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='KindsList',
            name='prize_kinds',
            field=models.CharField(max_length=30),
        ),
    ]
