# Generated by Django 5.0.6 on 2024-06-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoveMusics', '0002_auto_20240618_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='MusicsInfo',
            old_name='likes_mill',
            new_name='score',
        ),
    ]
