# Generated by Django 5.0.6 on 2024-06-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoveMusics', '0003_auto_20240618_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicsScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=10)),
            ],
        ),
    ]
